#!/usr/bin/env bash

echo Testing fibonacci.py
nosetests --no-byte-compile fibonacci.py
echo
echo

echo Testing closure.py
nosetests --no-byte-compile closure.py
echo 
echo

echo Testing pascal.py
nosetests --no-byte-compile pascal.py
echo 
echo
